app:
  name: "READMEOW"
  version: "1.0.0"

server:
  host: "0.0.0.0"
  port: "${SERVER_PORT}"
  writeTimeout: 10
  readTimeout: 10
  idleTimeout: 30
  requestTimeout: 10
  closeTimeout: 30

auth:
  secret: "${SECRET}"
  tokenTTL: 4320

storage:
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  database: "${POSTGRES_DB}"
  timezone: "Europe/Moscow"
  host: "${POSTGRES_HOST}"
  port: "${POSTGRES_PORT}"
  sslMode: "${SSL_MODE}"
  connectTimeout: 5

cache:
  host: "redis"
  port: "${REDIS_PORT}"
  password: "${REDIS_PASSWORD}"
  connectTimeout: 5

search:
  host: "es"
  port: "${ELASTICSEARCH_PORT}"
  user: "${ELASTICSEARCH_USER}"
  password: "${ELASTICSEARCH_PASSWORD}"
  timeout: 60
  pingTimeout: 5