app:
  name: "READMEOW"
  version: "1.0.0"

server:
  host: "0.0.0.0"
  port: "${SERVER_PORT}"
  writeTimeout: 10
  readTimeout: 10
  idleTimeout: 30
  requestTimeout: 10
  closeTimeout: 30

auth:
  secret: "${SECRET}"
  codeTTL: 300
  codeAttempts: 5
  tokenTTL: 259200

storage:
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  database: "${POSTGRES_DB}"
  timezone: "Europe/Moscow"
  host: "postgres"
  port: "${POSTGRES_PORT}"
  sslMode: "${SSL_MODE}"
  connectTimeout: 10
  amountOfConns: 15

cache:
  host: "redis"
  port: "${REDIS_PORT}"
  password: "${REDIS_PASSWORD}"
  connectTimeout: 5

search:
  host: "es"
  port: "${ELASTICSEARCH_PORT}"
  user: "${ELASTICSEARCH_USER}"
  password: "${ELASTICSEARCH_PASSWORD}"
  timeout: 60
  pingTimeout: 5

email:
  name: "Readmeow Register System"
  address: "kiryuhakipyatok@gmail.com"
  password: "${EMAIL_PASSWORD}"
  smtpAddress: "smtp.gmail.com"
  smtpServerAddress: "smtp.gmail.com:587"

sheduler:
  widgetBulkTime: 4
  widgetBulkTimeout: 5 
  templateBulkTime: 2
  templateBulkTimeout: 5
  cleanCodesTime: 1
  cleanCodesTimeout: 5
